name: fox_logging
description: Utilities for the logging packge like Formatter, Sinks,... It 
  provides a flow to make logging more structured by introducing sinks and 
  formatters.
version: 0.1.0
homepage: https://github.com/wim07101993/fox_logging
repository: https://github.com/wim07101993/fox_logging/tree/master/packages/fox_logging

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  ansicolor: ">=2.0.0 <3.0.0"
  logging: ">=1.0.0 <2.0.0"

dev_dependencies:
  faker: ">=2.0.0 <3.0.0"
  lint: 
  mocktail: ">0.0.0 <1.0.0"
  test: ">=1.0.0 <2.0.0"
