name: logging_extensions
description: Utilities for the logging packge like Formatter, Sinks,... It 
  provides a flow to make logging more structured by introducing sinks and 
  formatters.
version: 0.0.1
homepage: https://github.com/wim07101993/logging_extensions
repository: https://github.com/wim07101993/logging_extensions


environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  ansicolor: ^2.0.1
  logging: ^1.0.2

dev_dependencies:
  faker: ^2.0.0
  lint: ^1.8.1
  mocktail: ^0.2.0
  test: ^1.20.1
