name: fox_logging
description: Utilities for the logging package like Formatter, Sinks,... It 
  provides a flow to make logging more structured by introducing sinks and 
  formatters.
homepage: https://github.com/wim07101993/fox_logging
repository: https://github.com/wim07101993/fox_logging
version: 1.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ansicolor: ">=2.0.0 <3.0.0"
  logging: ">=1.0.0 <2.0.0"

dev_dependencies:
  faker: ">=2.0.0 <3.0.0"
  lint: 
  mocktail: ">1.0.0 <2.0.0"
  test: ">=1.0.0 <2.0.0"
  test_process: ">=2.0.0 <3.0.0"