name: logging_extensions
description: Extensions for the logging package.
version: 0.0.1


environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  ansicolor: ^2.0.1
  logging: ^1.0.2

dev_dependencies:
  faker: ^2.0.0
  lint: ^1.7.2
  mocktail: ^0.2.0
  test: ^1.19.5
