name: flutter_fox_logging
description: A widget library for the `fox_logging` package. Can be used to display the logs of an app.
version: 1.1.0
homepage: https://github.com/wim07101993/fox_logging
repository: https://github.com/wim07101993/fox_logging/tree/master/packages/flutter_fox_logging

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fox_logging: ">=0.0.0 <1.0.0"

dev_dependencies:
  async:
  faker:
  flutter_test:
    sdk: flutter
  lint:
  mocktail:

flutter:
