name: Test dart code

inputs:
  working-directory:
    required: true
  flutter-or-dart:
    type: choice
    default: dart
    options:
      - dart
      - flutter
  min-coverage:
    default: 90
    
runs:
  using: "composite"
  steps:
    - name: Install dart
      if: inputs.flutter-or-dart == 'dart'
      uses: dart-lang/setup-dart@v1.4
      
    - name: Install flutter
      if: inputs.flutter-or-dart == 'flutter'
      uses: subosito/flutter-action@v2.8.0

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ${{ inputs.flutter-or-dart }} pub get
        ${{ inputs.flutter-or-dart }} pub global activate coverage
        
    - name: Run dart tests
      if: inputs.flutter-or-dart == 'dart'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: dart test --coverage=coverage && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib
        
    - name: Run flutter tests
      if: inputs.flutter-or-dart == 'flutter'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: flutter test --coverage

    - name: Check code coverage
      uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
      with:
        min_coverage: ${{ inputs.min-coverage }}
        path: ${{ inputs.working-directory }}/coverage/lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        ignore: 
          - **/.github
          - **/.idea
          - **/examples
          - **/example
