name: Test dart code

inputs:
  working-directory:
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Install dart
      uses: dart-lang/setup-dart@v1.4

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        dart pub get
        dart pub global activate coverage
        
    - name: Run Tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: dart test --coverage=coverage && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib

    - name: Check Code Coverage
      uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
      with:
        min_coverage: 90
        path: ${{ inputs.working-directory }}/coverage/lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.1      
