name: Publish to pub.dev

on:
  workflow_dispatch:
  push:
    tags:
    - 'fox-logging-v[0-9]+.[0-9]+.[0-9]+*' # tag pattern on pub.dev: 'v'
    
jobs:
  publish:
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: packages/fox_logging
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: getVersion
        uses: gittools/actions/gitversion/execute@v0.9.7
        
      - name: Update versino in pubspec
        run: 'sed -i -E "s/^version: .*/version: ${{ getVersion.outputs.fullSemVer }}/g" pubspec.yaml'
        
      - run: cat pubspec.yaml
      
#       - uses: dart-lang/setup-dart@v1
      
#       - name: Install dependencies
#         run: dart pub get
        
#       - name: Publish
#         run: dart pub publish --force
