name: Test Fox Logging

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ensure code quality
        uses: "./.github/workflows/templates/ensure_code_quality"
        with:
          working-directory: packages/fox_logging
      
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        uses: "./.github/workflows/templates/test_dart_code"
        with:
          working-directory: packages/fox_logging
